//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.18 at 03:48:40 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://alpha.com/ordervalidity/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.alpha.ordervalidity.Model;
